edgexfoundry/go-mod-messaging

pkg/types/message_envelope.go

This commit resolves issue #16
Added Event checksum identifier to message envelop.
Also added a new function for creating a message envelope with a checksum. I left the existing function as is to not break any other services that leverage that function.
Signed-off-by: Anthony M. Bonafide <AnthonyMBonafide@gmail.com>

Added Checksum information to envelop

---

internal/pkg/zeromq/client.go

This PR address issues edgexfoundry/edgex-go#1512 & #28
Details of the defect are in #28

bug(zmq race condition): Lock call to ZMQs SendMessage to make it thread safe

---

Attribution.txt
README.md
go.mod
internal/pkg/mqtt/client.go
internal/pkg/mqtt/client_integration_test.go
internal/pkg/mqtt/client_options.go
internal/pkg/mqtt/client_options_test.go
internal/pkg/mqtt/client_test.go
internal/pkg/mqtt/errors.go
messaging/factory.go
messaging/factory_test.go

Fix #36
Create implementation of Client which communicates with an MQTT server
to provide the necessary functionality.
Add unit tests for new MQTT client
Update Attribution.txt to include the newly import library
'eclipse/paho.mqtt.golang'.
Add integration tests which are disabled by default and are enable via
Go's test tag integration(See documentation in client_integration_test
file). The integration tests use a MQTT server to test the MQTT clients
functionality since there were functional gaps missing in the unit tests
which are better handled with integration tests.
Signed-off-by: Anthony M. Bonafide <AnthonyMBonafide@gmail.com>

Add support for MQTT

---

README.md
internal/pkg/errors.go
internal/pkg/mqtt/client.go
internal/pkg/mqtt/client_integration_test.go
internal/pkg/mqtt/client_options.go
internal/pkg/mqtt/client_options_test.go
internal/pkg/mqtt/client_test.go
messaging/mqtt/configuration.go
messaging/mqtt/configuration_test.go
messaging/mqtt/constants.go

Fix #41
Update MQTT client, client options, and constructors to allow for
configuration of TLS communication.
Create a helper file configuration.go which contains a struct and
methods which will aid users in creating optional configuration
properties when creating a MQTT client
Update tests to cover newly added functionality.
Updated README to reference the newly added configuration.go file for
creating configuration properties.
Signed-off-by: Anthony M. Bonafide <AnthonyMBonafide@gmail.com>

Add TLS Support For MQTT Client

---

internal/pkg/redis/streams/client.go
internal/pkg/redis/streams/configuration_options.go
internal/pkg/redis/streams/configuration_options_test.go

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.
Setting password in Optional with key "Password" is ignored. 
Setting password in Optional with key "password" is fails due to reflection can't set private field. 
Setting password in Optional with key "Password" works properly. 
Setting password in Optional with key "password" is ignored properly 
Are there any new imports or modules? If so, what are they used for and why?
no

fix(redisstreams): Properly set Password via reflection when found in Options

---

internal/pkg/zeromq/client_test.go
pkg/types/message_envelope.go

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.
CorrelationID is passed in the Context. The key to extracted it from the context
changed to match the key used in the HTTP Header.
Key constant update to latest correct value.
Are there any new imports or modules? If so, what are they used for and why?
no

fix: Change CorrelationID key constant to match recent change in edgex-go

---

go.mod
internal/pkg/mqtt/client_integration_test.go
internal/pkg/redis/streams/client_test.go

Signed-off-by: lenny <leonard.goodell@intel.com>
Missed a couple v2 update in imports which cause the IDE to add v0.x.x version in the go.mod file.
All import paths now have v2 and module does import its older self.

fix: Adjusted missing v2 in remaining paths

---

go.mod
internal/pkg/mqtt/client_test.go

Latest Paho module breaks build as the new Done API was add that our MockToken doesn't implement
Update to latest Paho module and added Done() func to the MockToken
- [x ] No

refactor: Add Done() method to MockToken for latest Paho module

---

internal/pkg/zeromq/client.go

`Publisher` is checked for nil outside the locked section that sets it, which causes a race condition.
`Publisher` is not checked outside the locked section that sets it, which resolves the race condition

fix: Resolve race condition in ZMQ impl when binding to port

---

internal/pkg/mqtt/client.go
internal/pkg/mqtt/client_test.go
internal/pkg/redis/streams/client.go
internal/pkg/redis/streams/client_test.go
internal/pkg/redis/streams/goredis.go
internal/pkg/zeromq/client.go
internal/pkg/zeromq/client_test.go
pkg/types/message_envelope.go

Obsolete Checksum property exists
Not property to indicate the topic the data was received on.
ReceivedTopic is set to the topic that the message was received for from the MessageBus
Obsolete Checksum property was removed
BREAKING CHANGE: Checksum property has been removed from the MessageEnvelope

feat: Add ReceivedTopic to MessageEnvelope & remove Checksum

---

Attribution.txt
internal/pkg/mqtt/client.go
internal/pkg/mqtt/client_test.go

Now WillQos and WillRetained are set from the values in configuration
fixes #112
Also removed unneeded Attribution.tx file
closes #32
**No docs change required**
Had to test these setting. temporarily added print statements to publish and subscribe to validate the values in the config are used.

fix: Use Qos and Retained value from configuration

---

internal/pkg/zeromq/linux_client.go
internal/pkg/zeromq/linux_client_test.go
internal/pkg/zeromq/linux_subscriber.go
internal/pkg/zeromq/linux_subscriber_test.go
internal/pkg/zeromq/windows_client.go
messaging/factory_test.go
messaging/linux_factory_test.go
messaging/windows_factory_test.go

This allows services that use this module to build native on windows with out installing the ZeroMQ dependency.
BREAKING CHANGE: This disables use of ZMQ when running windows native builds.
**TBD**
- Run no-secure EdgeX stack and stop Core Data
- Update edgex-go go.mod to use the branch for this PR for go-mod-messaging
- Build Core Data native on windows
- Change LogLevel for Core Data to DEBUG
- Run Core Data native on windows with `EDGEX_SECURITY_SECRET_STORE=false`
- Verify …

refactor: Disable use of ZMQ on native windows via conditional builds

---

internal/pkg/zeromq/client.go
internal/pkg/zeromq/client_test.go
internal/pkg/zeromq/subscriber.go
internal/pkg/zeromq/subscriber_test.go

closes #131
Use branch in edgex-go
Build edgex-go on Linus & Windows and Mac if has access
**N/A**

fix: Adjust build constraints to allow ZMQ on all OSes except Windows

---

Makefile
internal/pkg/redis/client.go
internal/pkg/redis/client_test.go

This is to avoid race condition when the loop iterates faster than go routines run. It fixes #130
Signed-off-by: Farshid Tavakolizadeh <farshid.tavakolizadeh@canonical.com>

fix: pass a copy of topic to redis subscriber

---

internal/pkg/redis/client.go

fixes #133
Use branch for this PR in App SDK template app
Configure template app subscriptions to be `SubscribeTopics="edgex/events/#,edgex/events/#"
Build and run template app
Verify fails with following message:
```
"failed to subscribe to topic(s) 'edgex/events/#,edgex/events/#': subscription for 'edgex/events/#' topic already exists, must be unique"
```

fix: Disallow subscribing to same exact topic multiple times

---

messaging/factory.go
messaging/factory_noop.go

Using this branch in edgex-go
Change core-metadata build back to GO and GOFLAG
Build and verify it fails due to ZMQ dependencies
Add `-tags no_messagebus` to core-metadata build
```
$(GO) build $(GOFLAGS) -tags no_messagebus -o $@ ./cmd/core-metadata
```
Verify builds and runs fine.

feat: Add build flag to build w/o messaging capability

---

internal/pkg/redis/client.go

fixes #133 for jakarta
Back port of https://github.com/edgexfoundry/go-mod-messaging/pull/140 for jakarta
Use branch for this PR in App SDK template app
Configure template app subscriptions to be `SubscribeTopics="edgex/events/#,edgex/events/#"
Build and run template app
Verify fails with following message:
```
"failed to subscribe to topic(s) 'edgex/events/#,edgex/events/#': subscription for 'edgex/events/#' topic already exists, must be unique"
```

fix: (jakarta) Disallow subscribing to same exact topic multiple times

---

internal/pkg/mqtt/client.go

fixes #153
uncovered and tested as part of App SDK InvalidMessagesReceived metric implementation and testing.

fix: Don't send invalid message as normal message from MQTT

---

internal/pkg/redis/client.go
internal/pkg/redis/client_test.go

Also avoids starving other threads/processes due tight loop sending
errors.
closes #156
Verified with App Template built with this branch
Stopped Redis
Verified logs not spammed and process not taking more than 10% of CPU.
Restarted Redis
Verified service received messages as expected

feat: Handle repeated error better to not spam logs

---

internal/pkg/config.go
internal/pkg/nats/README.md
internal/pkg/nats/client.go
internal/pkg/nats/jetstream/client.go
internal/pkg/nats/options.go
internal/pkg/nats/options_test.go

Leverages existing infrastructure to add TLS support for clients
connecting to broker using TLS or NATS schemes.
Fixes #147 
Signed-off-by: Alex Ullrich <alex.ullrich@gmail.com>
I don't think TLS is really documented currently for anything open to suggestions on how to add.
Configure broker to run with TLS and adjust client configurations accordingly (setup via `MessageBusConfig.Optional` should mimic whats done for MQTT or Redis currently): https://docs.nats.io/running-a-nats-service/configuration/securing_nats/tls

feat: NATS Client TLS Support

---

internal/pkg/config.go
internal/pkg/constants.go
internal/pkg/mqtt/client.go
internal/pkg/mqtt/client_test.go
internal/pkg/nats/options.go
internal/pkg/redis/client.go
internal/pkg/redis/client_test.go

Fix: #142 
Signed-off-by: Felix Ting <felix@iotechsys.com>

feat: Allow user to bring their own CA in the client

---

internal/pkg/nats/marshaller.go
internal/pkg/nats/marshaller_test.go
pkg/types/message_envelope.go
pkg/types/message_envelope_test.go

to support north-south messaging implementation
fix #160
Signed-off-by: Chris Hung <chris@iotechsys.com>
Add new dependency: https://github.com/edgexfoundry/go-mod-core-contracts
to access the common constants in EdgeX

feat: add new fields and factory functions for MessageEnvelope 

---

internal/pkg/nats/options.go
internal/pkg/nats/options_test.go
internal/pkg/nats/testdata/nkey.seed

Only supporting file-based options at the moment to avoid keeping key in
memory.  Fixes #167.
Signed-off-by: Alex Ullrich <alex.ullrich@gmail.com>
will see on timing if this should go in Levski docs
This is useful for setting up a local broker to perform NKEYS auth: https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/nkey_auth
Or setup a memory resolver for testing JWT auth via credentials file: https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/jwt/mem_resolver

feat: Add File-Based NKEY & Credentials Auth to NATS Client

---

README.md
internal/pkg/mqtt/client_integration_test.go
internal/pkg/mqtt/client_options.go
internal/pkg/mqtt/client_options_test.go
internal/pkg/mqtt/client_test.go
internal/pkg/nats/client_test.go
internal/pkg/nats/options.go
internal/pkg/nats/options_test.go
internal/pkg/redis/client.go
internal/pkg/redis/client_integration_test.go
internal/pkg/redis/client_test.go
messaging/factory.go
messaging/factory_nats_test.go
messaging/factory_no_nats_test.go
messaging/factory_test.go
messaging/mqtt/configuration_test.go
pkg/types/host_info.go
pkg/types/types.go

BREAKING CHANGE: Configuration now only needs  single broker host info
closes #196

refactor!: Reduce MessageBus config to have a single host

---

clients/command.go
clients/command_test.go
go.mod
go.sum

BREAKING CHANGE: ds-pushevent and ds-returnevent to use bool true/false instead of yes/no
related: https://github.com/edgexfoundry/go-mod-core-contracts/pull/782
Signed-off-by: Ginny Guan <ginny@iotechsys.com>
https://github.com/edgexfoundry/edgex-docs/pull/917
build core-command and device-virtual docker images based on the changes and run docker-compose.yml
The following commands work as expected:
```
curl http://localhost:59882/api/v2/device/name/Random-Boolean-Device/Bool\?ds-pushevent\=true
curl …
```

refactor!: Use bool types for command parameters to be more consistent

---

internal/pkg/redis/client.go
internal/pkg/redis/client_test.go

BREAKING CHANGE: implement the topic conversion between Redis Pub/sub wild card `*` and MQTT wild cards `+` for single level and `#` for multiple levels
close #166
Signed-off-by: Ginny Guan <ginny@iotechsys.com>
1. Update device-virtual system event topic to `edgex/system-events/core-metadata/device/+/device-virtual/#`
2. Build and run device-virtual
3. Receive system events correctly

refactor!: Refactor Redis Pub/sub topic wild cards to match that of MQTT

---

clients/command.go
clients/command_test.go
go.mod
go.sum

BREAKING CHANGE: Topics no longer in config. Client factory method has additional baseTopic parameter
<TBD

refactor!: Replace topics from config with new constants

---

internal/pkg/redis/client.go
internal/pkg/redis/client_integration_test.go
internal/pkg/redis/client_test.go
internal/pkg/redis/goredis.go
internal/pkg/redis/mocks/RedisClient.go
internal/pkg/redis/types.go

This should avoid too many open files in Redis.
Tested with Redis Integration tests as well as Core Metadata adding devices.

fix: Optimize Redis Unsubscribe so the subscriptions are closed and removed

---

internal/pkg/redis/client.go
internal/pkg/redis/client_test.go
internal/pkg/redis/goredis.go
internal/pkg/redis/mocks/RedisClient.go
internal/pkg/redis/types.go

check client subscribes to topic successfully by examining if the first received message is subscribe confirmation message.
reference:
- https://github.com/redis/go-redis/issues/575#issuecomment-311994859
- https://redis.io/commands/psubscribe/#return
closes #227

fix: assure redis correctly subscribe to topic before receiving

---

internal/pkg/nats/marshaller_test.go
pkg/types/message_envelope.go
pkg/types/message_envelope_test.go

Not a breaking change as original thought.
closes #169

refactor: Add JSON attributes to MessageEnvelope fields

---

go.mod
go.sum
internal/pkg/nats/marshaller_test.go
pkg/types/message_envelope.go
pkg/types/message_envelope_test.go

BREAKING CHANGE: apiVersion in MessageEnvelope is changed to v3
also reuse common constants in go-mod-core-contracts.
1. Build and run core-command and device-virtual from this branch
2. Verify `apiVersion: v3` is required in the MessageEnvelope

feat!: update API version to v3

---

internal/pkg/redis/client.go

fixes #246
Modify Device simple to have buffered channels for all channels use in subscribe
Build SDK Device Simple using this branch
Run Device Simple with just `-cp`
Verify service no longer hangs.

fix: (WIP) Resolve hang issue when Redis Subscribe fails

---

clients/command.go
clients/command_test.go

Add enableNameFieldEscape parameter to CommandClient and encode MessageBus topic path
- Run unit test
- Test the client with core command

feat: Encode MessageBus topic path

---

pkg/types/message_envelope.go

handle the previous nil []byte payload correctly
related: https://github.com/edgexfoundry/go-mod-messaging/pull/384

fix: not to marshal nil payload if EDGEX_MSG_BASE64_PAYLOAD==true

---

pkg/types/message_envelope.go

- remove bytes conversion from NewMessageEnvelopeWithError
- add function IsMsgBase64Payload

feat: Add error check for NewMessageEnvelope

---

internal/pkg/mqtt/client.go
internal/pkg/mqtt/errors.go

fix: #420 
Run core-command with the go-mod-messaging module from this branch, and verify that sending command requests via message bus works properly.

fix: Ensure Unsubscribe waits for operation completion using getTokenError

---

internal/pkg/criticalops.go
internal/pkg/mqtt/client.go
internal/pkg/nats/client.go
internal/pkg/noopclient.go
messaging/interface.go

fix: #435 
- Add CriticalOperationSignaler interface and implementation
- Extend MessageClient interface to MessageClientExt with critical operation signaling support
- Integrate critical operation signaler into MQTT and NATS clients

feat: Implement critical operation signaler

---

internal/pkg/criticalops.go

Since each registered critical operation removes itself from the map in RegisterCriticalOperation once finished, this clearing is redundant.

fix: Remove redundant clearing of criticalOperations from WaitForCriticalOperations
