pkg/types/message_envelope.go
pkg/types/message_envelope_test.go
pkg/types/types.go

Implemented NewMessageEnvelope

---

pkg/types/message_envelope.go

Fixed value for contentType constant to match that in go-mod-core-contracts

---

Makefile
pkg/types/message_envelope.go
pkg/types/message_envelope_test.go

Added gofmt to test target in make and run it

---

internal/pkg/zeromq/client.go
internal/pkg/zeromq/client_test.go
pkg/types/types.go

This PR addresses issue #18. 
Changes to Export Service will be handling in current CBOR PR 
A new issue to update App Functions has been added.

Changed TopicChannel to no longer use a pointer

---

internal/pkg/zeromq/client.go

Fix #25
Utilized mutex to prevent more than one goroutine from attempting to
bind to the ZeroMQ port when client is initialized. When this happens
it can leave the client in an unknonw state.
Signed-off-by: Trevor Conn <trevor_conn@dell.com>

Handle concurrent attempts to bind to port address

---

.gitignore
Dockerfile.build
Dockerfile.build-arm64
Jenkinsfile
Makefile

Signed-off-by: Tyler Powers <tyler.m.powers@intel.com>

Add code coverage output to codecov

---

Dockerfile.build
Jenkinsfile
go.mod

Update relevant files in go-mod-messaging for Go 1.13.

---

internal/pkg/mqtt/client_options.go
internal/pkg/mqtt/client_test.go

The fix patch for [this issue](https://github.com/edgexfoundry/go-mod-messaging/issues/50)

fix MQTT subscriber host issue

---

README.md

Signed-off-by: lenny <leonard.goodell@intel.com>
What kind of change does this PR introduce?
Issue Number: None

fix: Fix documentation typo in README to new semver tag is created.

---

internal/pkg/mqtt/client.go
internal/pkg/mqtt/client_test.go

Subscriptions are lost when connection is lost and reestablished
Subscriptions are re-created when connection is reestablished

fix: Add ability to re-subscribe to topics when reconnected

---

internal/pkg/mqtt/client_test.go

Unit test was missing check for err != nil before accessing err
Unit test checks for err != nil before accessing err

fix: Fix panic in unit tests.

---

.golangci.yml
Makefile
internal/pkg/config.go
internal/pkg/mqtt/client_options.go
internal/pkg/mqtt/client_test.go
internal/pkg/zeromq/linux_client.go
internal/pkg/zeromq/linux_client_test.go
pkg/types/message_envelope.go
pkg/types/message_envelope_test.go

Fixes #118
Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>
N/A
```make test```

feat(security): Enable gosec and default linter set

---

README.md
internal/pkg/redis/client.go
internal/pkg/redis/types.go

Replace RedisStreams with Redis Pub/Sub in README and GoDoc
Replace single quote in TOML example with double quotes
Close #123
N/A, only update docs

docs: Update README and GoDoc

---

go.mod

build: Bump Go version to 1.18 in go.mod

---

Makefile
internal/pkg/zeromq/client.go
internal/pkg/zeromq/client_test.go
internal/pkg/zeromq/noop_client.go
internal/pkg/zeromq/subscriber.go
internal/pkg/zeromq/subscriber_test.go
messaging/linux_factory_test.go
messaging/no_zmq_factory_test.go

feat: Add no_zmq build flag

---

clients/command.go
clients/command_test.go

Signed-off-by: Chris Hung <chris@iotechsys.com>

feat: update query request topic naming

---

go.mod
go.sum

Signed-off-by: Chris Hung <chris@iotechsys.com>

build: bump go-mod-core-contracts

---

go.mod
go.sum

build: Update to use released go-mods

---

go.mod
go.sum

fix: Use latest core contracts module for constant name fix

---

internal/pkg/redis/client.go

Fixes issue with new Request API on Redis

fix: Combine defers in Redis Unsubscribe so Unlock occurs first

---

internal/pkg/redis/client_test.go

- [] I have fully tested (add details below) this the new feature or bug fix (if not, why?)

fix: Rework unsubscribe test to not fail randomly

---

internal/pkg/redis/goredis.go

related to edgexfoundry/device-sdk-go#1366
1. Build device-virtual based on this branch and run with other edgex services
2. Successfully receive deviceservice system event
- add
```
level=DEBUG ts=2023-03-12T06:15:41.696054359Z app=device-virtual source=callback.go:58 msg="System event received on message queue. Topic: edgex/system-events/core-metadata/deviceservice/add/device-virtual, Correlation-id: f97736f7-b7dd-478e-8db4-1718ea8886b1"
```
- update the device service adminState from UNLOCKED to LOCKED
``` …
```

fix: subscribe redis topic for empty suffix to match MQTT multi-level wildcard

---

CHANGELOG.md
go.mod
go.sum

docs: Update changelog for 3.0 and use released core-contracts

---

Makefile
go.mod
go.sum

build: Upgrade to go 1.21 and linter 1.54.2

---

go.mod
go.sum

build: Update to released Core Contracts

---

go.mod
go.sum

build: Update to latest core contracts

---

.github/dependabot.yml

build: Change the depedenbot to daily check

---

internal/pkg/nats/client.go
internal/pkg/request.go
pkg/types/message_envelope.go

feat: Wrap errors by using %w verb for clearer error details

---

go.mod
go.sum
vendor/github.com/edgexfoundry/go-mod-core-contracts/v4/dtos/address.go
vendor/github.com/edgexfoundry/go-mod-core-contracts/v4/dtos/autoevent.go
vendor/github.com/edgexfoundry/go-mod-core-contracts/v4/dtos/reading.go
vendor/modules.txt

build: Update to new go-mod-contracts 4.0.1 for odessa
